"use client";

import * as React from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/dashboard/ui/card";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/dashboard/ui/tabs";
import { Badge } from "@/components/dashboard/ui/badge";
import { Button } from "@/components/dashboard/ui/button";
import { Input } from "@/components/dashboard/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/dashboard/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/dashboard/ui/table";
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "@/components/dashboard/ui/chart";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  LineChart,
  Line,
  Legend,
} from "recharts";
import {
  Shield,
  ShieldAlert,
  Search,
  Clock,
  FileText,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Download,
  ExternalLink,
  Lock,
  Users,
  Key,
  FileCheck,
  Gavel,
  History,
  ChevronRight,
  Filter,
  Calendar,
  Eye,
} from "lucide-react";
import { cn } from "@/lib/utils";
import Link from "next/link";

// ==================== TYPES & INTERFACES ====================

export type ComplianceFramework =
  | "ISO27001"
  | "SOC2"
  | "NIS2"
  | "ZERO_TRUST"
  | "INTERNAL_POLICY"
  | "CONTRACTUAL";

export type ControlStatus =
  | "compliant"
  | "partial"
  | "non-compliant"
  | "not-applicable";

export interface ComplianceControl {
  id: string;
  name: string;
  description: string;
  framework: ComplianceFramework;
  frameworkName: string;
  status: ControlStatus;
  category: string;
  justification: string;
  evidenceSources: string[];
  lastAssessed: string;
  nextAssessmentDue: string;
  remediationDeadline?: string;
  assignedTo?: string;
  riskLevel: "low" | "medium" | "high" | "critical";
  autoGenerated: boolean;
}

export interface ComplianceFrameworkSummary {
  id: ComplianceFramework;
  name: string;
  version: string;
  score: number;
  totalControls: number;
  compliant: number;
  partial: number;
  nonCompliant: number;
  notApplicable: number;
  lastAuditDate: string;
  nextAuditDue: string;
  auditor?: string;
}

export interface ComplianceTrend {
  date: string;
  score: number;
  compliant: number;
  nonCompliant: number;
}

export interface IdentityComplianceItem {
  id: string;
  type:
    | "privileged"
    | "dormant"
    | "token_expiry"
    | "over_permissioned"
    | "no_mfa";
  subjectId: string;
  subjectName: string;
  subjectType: string;
  severity: "low" | "medium" | "high" | "critical";
  description: string;
  detectedAt: string;
  linkedReport: string;
  linkedReportUrl: string;
}

export interface PolicyComplianceItem {
  id: string;
  policyId: string;
  policyName: string;
  status: "active" | "inactive" | "draft";
  coverage: number;
  exceptionsCount: number;
  inheritedRules: number;
  explicitRules: number;
  lastModified: string;
  enforcementRate: number;
}

export interface ComplianceEvidence {
  id: string;
  controlId: string;
  type: "log" | "policy" | "access_decision" | "audit_trail" | "certificate";
  title: string;
  timestamp: string;
  subjectId?: string;
  subjectName?: string;
  details: Record<string, unknown>;
  hash: string;
  integrityVerified: boolean;
}

export interface ComplianceGap {
  id: string;
  controlId: string;
  controlName: string;
  framework: string;
  severity: "low" | "medium" | "high" | "critical";
  description: string;
  detectedAt: string;
  remediationDeadline?: string;
  daysOverdue?: number;
}

export interface ComplianceSummary {
  overallScore: number;
  previousScore: number;
  trendDirection: "up" | "down" | "stable";
  totalControls: number;
  compliantCount: number;
  partialCount: number;
  nonCompliantCount: number;
  gapCount: number;
  highRiskGaps: number;
  frameworks: ComplianceFrameworkSummary[];
  trend: ComplianceTrend[];
  lastUpdated: string;
}

// ==================== MOCK DATA ====================

const COMPLIANCE_SUMMARY: ComplianceSummary = {
  overallScore: 87.3,
  previousScore: 84.1,
  trendDirection: "up",
  totalControls: 156,
  compliantCount: 124,
  partialCount: 18,
  nonCompliantCount: 14,
  gapCount: 23,
  highRiskGaps: 5,
  frameworks: [
    {
      id: "ISO27001",
      name: "ISO 27001/27002",
      version: "2022",
      score: 91.2,
      totalControls: 58,
      compliant: 48,
      partial: 6,
      nonCompliant: 4,
      notApplicable: 0,
      lastAuditDate: "2024-11-15",
      nextAuditDue: "2025-11-15",
    },
    {
      id: "SOC2",
      name: "SOC 2 Type II",
      version: "Trust Services Criteria",
      score: 89.5,
      totalControls: 42,
      compliant: 34,
      partial: 5,
      nonCompliant: 3,
      notApplicable: 0,
      lastAuditDate: "2024-10-20",
      nextAuditDue: "2025-10-20",
    },
    {
      id: "NIS2",
      name: "NIS2 Directive",
      version: "EU 2022/2555",
      score: 82.1,
      totalControls: 35,
      compliant: 26,
      partial: 5,
      nonCompliant: 4,
      notApplicable: 0,
      lastAuditDate: "2024-12-01",
      nextAuditDue: "2025-06-01",
    },
    {
      id: "ZERO_TRUST",
      name: "Zero Trust Architecture",
      version: "NIST SP 800-207",
      score: 78.4,
      totalControls: 21,
      compliant: 16,
      partial: 2,
      nonCompliant: 3,
      notApplicable: 0,
      lastAuditDate: "2025-01-10",
      nextAuditDue: "2025-07-10",
    },
  ],
  trend: [
    { date: "2024-08", score: 81.2, compliant: 118, nonCompliant: 22 },
    { date: "2024-09", score: 82.5, compliant: 120, nonCompliant: 20 },
    { date: "2024-10", score: 83.1, compliant: 121, nonCompliant: 19 },
    { date: "2024-11", score: 84.1, compliant: 122, nonCompliant: 18 },
    { date: "2024-12", score: 85.6, compliant: 123, nonCompliant: 16 },
    { date: "2025-01", score: 87.3, compliant: 124, nonCompliant: 14 },
  ],
  lastUpdated: "2025-02-09T10:30:00Z",
};

const COMPLIANCE_CONTROLS: ComplianceControl[] = [
  {
    id: "ctrl-001",
    name: "Least Privilege Enforcement",
    description:
      "All identities must operate with minimum necessary permissions",
    framework: "ISO27001",
    frameworkName: "ISO 27001/27002",
    status: "compliant",
    category: "Access Control",
    justification:
      "Policy engine actively enforces least privilege across all access requests. All identities reviewed quarterly.",
    evidenceSources: ["/platform/policy", "/report/privilege"],
    lastAssessed: "2025-02-01",
    nextAssessmentDue: "2025-05-01",
    riskLevel: "high",
    autoGenerated: true,
  },
  {
    id: "ctrl-002",
    name: "MFA for Privileged Access",
    description:
      "Multi-factor authentication required for all privileged accounts",
    framework: "SOC2",
    frameworkName: "SOC 2 Type II",
    status: "partial",
    category: "Authentication",
    justification:
      "85% of privileged accounts have MFA enabled. 15 accounts require enforcement.",
    evidenceSources: ["/report/access", "/security/audit"],
    lastAssessed: "2025-02-05",
    nextAssessmentDue: "2025-03-05",
    remediationDeadline: "2025-03-15",
    assignedTo: "security-team@aether.io",
    riskLevel: "critical",
    autoGenerated: true,
  },
  {
    id: "ctrl-003",
    name: "Dormant Account Review",
    description:
      "Inactive accounts must be reviewed and disabled after 90 days",
    framework: "ISO27001",
    frameworkName: "ISO 27001/27002",
    status: "non-compliant",
    category: "Identity Lifecycle",
    justification:
      "47 dormant accounts detected without proper review. 12 accounts inactive > 180 days.",
    evidenceSources: ["/report/dormant"],
    lastAssessed: "2025-02-08",
    nextAssessmentDue: "2025-03-08",
    remediationDeadline: "2025-02-20",
    assignedTo: "identity-team@aether.io",
    riskLevel: "high",
    autoGenerated: true,
  },
  {
    id: "ctrl-004",
    name: "Access Review Cycle",
    description: "Quarterly access reviews for all privileged identities",
    framework: "SOC2",
    frameworkName: "SOC 2 Type II",
    status: "compliant",
    category: "Governance",
    justification:
      "Q4 2024 review completed. 234 identities reviewed, 12 access rights revoked.",
    evidenceSources: ["/security/audit"],
    lastAssessed: "2024-12-31",
    nextAssessmentDue: "2025-03-31",
    riskLevel: "medium",
    autoGenerated: false,
  },
  {
    id: "ctrl-005",
    name: "Token Expiration Policy",
    description: "All API tokens must have expiration dates ≤ 1 year",
    framework: "NIS2",
    frameworkName: "NIS2 Directive",
    status: "partial",
    category: "Credential Management",
    justification: "89% compliance. 23 tokens without expiration detected.",
    evidenceSources: ["/report/access"],
    lastAssessed: "2025-02-07",
    nextAssessmentDue: "2025-03-07",
    remediationDeadline: "2025-03-01",
    riskLevel: "medium",
    autoGenerated: true,
  },
  {
    id: "ctrl-006",
    name: "Zero Trust Network Access",
    description: "All access verified regardless of network location",
    framework: "ZERO_TRUST",
    frameworkName: "Zero Trust Architecture",
    status: "compliant",
    category: "Network Security",
    justification:
      "ZTNA policies enforced across all environments. No trusted network assumptions.",
    evidenceSources: ["/platform/policy", "/report/access"],
    lastAssessed: "2025-01-15",
    nextAssessmentDue: "2025-04-15",
    riskLevel: "high",
    autoGenerated: true,
  },
];

const IDENTITY_COMPLIANCE_ITEMS: IdentityComplianceItem[] = [
  {
    id: "id-comp-001",
    type: "privileged",
    subjectId: "user-123",
    subjectName: "admin.smith@enterprise.com",
    subjectType: "user",
    severity: "critical",
    description:
      "Over-provisioned admin account with 234 permissions across 12 roles",
    detectedAt: "2025-02-08T14:30:00Z",
    linkedReport: "Privilege Report",
    linkedReportUrl: "/admin/report/privilege",
  },
  {
    id: "id-comp-002",
    type: "dormant",
    subjectId: "user-456",
    subjectName: "j.doe@enterprise.com",
    subjectType: "user",
    severity: "high",
    description: "Account inactive for 187 days, last login 2024-08-05",
    detectedAt: "2025-02-09T08:00:00Z",
    linkedReport: "Dormant Accounts",
    linkedReportUrl: "/admin/report/dormant",
  },
  {
    id: "id-comp-003",
    type: "no_mfa",
    subjectId: "svc-789",
    subjectName: "legacy-api-service",
    subjectType: "service",
    severity: "critical",
    description: "Privileged service account without MFA enforcement",
    detectedAt: "2025-02-07T16:45:00Z",
    linkedReport: "Access Report",
    linkedReportUrl: "/admin/report/access",
  },
  {
    id: "id-comp-004",
    type: "token_expiry",
    subjectId: "token-abc",
    subjectName: "integration-token-prod",
    subjectType: "token",
    severity: "medium",
    description: "API token without expiration date, created 2023-06-15",
    detectedAt: "2025-02-06T10:20:00Z",
    linkedReport: "Access Report",
    linkedReportUrl: "/admin/report/access",
  },
];

const POLICY_COMPLIANCE_ITEMS: PolicyComplianceItem[] = [
  {
    id: "pol-comp-001",
    policyId: "pol-001",
    policyName: "Require MFA for Production",
    status: "active",
    coverage: 94.5,
    exceptionsCount: 3,
    inheritedRules: 12,
    explicitRules: 8,
    lastModified: "2025-01-20",
    enforcementRate: 99.2,
  },
  {
    id: "pol-comp-002",
    policyId: "pol-002",
    policyName: "IP Whitelist - Corporate",
    status: "active",
    coverage: 100,
    exceptionsCount: 0,
    inheritedRules: 4,
    explicitRules: 6,
    lastModified: "2024-12-15",
    enforcementRate: 100,
  },
  {
    id: "pol-comp-003",
    policyId: "pol-003",
    policyName: "Time-based Access Window",
    status: "active",
    coverage: 78.3,
    exceptionsCount: 12,
    inheritedRules: 2,
    explicitRules: 15,
    lastModified: "2025-02-01",
    enforcementRate: 95.7,
  },
];

const COMPLIANCE_GAPS: ComplianceGap[] = [
  {
    id: "gap-001",
    controlId: "ctrl-003",
    controlName: "Dormant Account Review",
    framework: "ISO 27001/27002",
    severity: "high",
    description: "47 dormant accounts without proper review cycle",
    detectedAt: "2025-02-08T10:00:00Z",
    remediationDeadline: "2025-02-20",
    daysOverdue: 0,
  },
  {
    id: "gap-002",
    controlId: "ctrl-002",
    controlName: "MFA for Privileged Access",
    framework: "SOC 2 Type II",
    severity: "critical",
    description: "15 privileged accounts without MFA enforcement",
    detectedAt: "2025-02-05T14:30:00Z",
    remediationDeadline: "2025-03-15",
  },
  {
    id: "gap-003",
    controlId: "ctrl-007",
    controlName: "Session Timeout Policy",
    framework: "NIS2 Directive",
    severity: "medium",
    description: "Session timeout not enforced for admin console",
    detectedAt: "2025-02-01T09:00:00Z",
    remediationDeadline: "2025-02-28",
  },
];

// ==================== CONSTANTS ====================

const FRAMEWORK_COLORS: Record<ComplianceFramework, string> = {
  ISO27001: "#3b82f6",
  SOC2: "#8b5cf6",
  NIS2: "#06b6d4",
  ZERO_TRUST: "#10b981",
  INTERNAL_POLICY: "#f59e0b",
  CONTRACTUAL: "#ec4899",
};

// ==================== COMPONENTS ====================

function TimeDisplay() {
  const [time, setTime] = React.useState<string>("");

  React.useEffect(() => {
    setTime(new Date().toLocaleString());
  }, []);

  return <span suppressHydrationWarning>{time}</span>;
}

function ComplianceScoreCard({ summary }: { summary: ComplianceSummary }) {
  const scoreChange = summary.overallScore - summary.previousScore;
  const isPositive = scoreChange > 0;

  return (
    <Card className="relative overflow-hidden">
      <div
        className={cn(
          "absolute top-0 right-0 w-32 h-32 -mr-8 -mt-8 rounded-full opacity-10",
          summary.overallScore >= 90
            ? "bg-green-500"
            : summary.overallScore >= 80
              ? "bg-yellow-500"
              : "bg-red-500",
        )}
      />
      <CardHeader className="pb-2">
        <CardTitle className="text-sm font-medium text-muted-foreground">
          Overall Compliance Score
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="flex items-baseline gap-2">
          <span className="text-5xl font-bold">
            {summary.overallScore.toFixed(1)}%
          </span>
          <span
            className={cn(
              "text-sm font-medium",
              isPositive ? "text-green-600" : "text-red-600",
            )}
          >
            {isPositive ? "+" : ""}
            {scoreChange.toFixed(1)}%
          </span>
        </div>
        <div className="mt-4 flex items-center gap-4 text-sm">
          <div className="flex items-center gap-1.5">
            <div className="h-2.5 w-2.5 rounded-full bg-green-500" />
            <span>{summary.compliantCount} Compliant</span>
          </div>
          <div className="flex items-center gap-1.5">
            <div className="h-2.5 w-2.5 rounded-full bg-yellow-500" />
            <span>{summary.partialCount} Partial</span>
          </div>
          <div className="flex items-center gap-1.5">
            <div className="h-2.5 w-2.5 rounded-full bg-red-500" />
            <span>{summary.nonCompliantCount} Non-compliant</span>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

function FrameworkCard({
  framework,
}: {
  framework: ComplianceFrameworkSummary;
}) {
  return (
    <Card className="hover:border-primary/50 transition-colors">
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between">
          <div>
            <CardTitle className="text-base">{framework.name}</CardTitle>
            <CardDescription className="text-xs mt-1">
              {framework.version}
            </CardDescription>
          </div>
          <div
            className={cn(
              "text-2xl font-bold",
              framework.score >= 90
                ? "text-green-600"
                : framework.score >= 80
                  ? "text-yellow-600"
                  : "text-red-600",
            )}
          >
            {framework.score}%
          </div>
        </div>
      </CardHeader>
      <CardContent className="pt-0">
        <div className="space-y-3">
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Total Controls</span>
            <span className="font-medium">{framework.totalControls}</span>
          </div>
          <div className="grid grid-cols-3 gap-2 text-xs">
            <div className="flex flex-col items-center p-2 rounded bg-green-500/10">
              <span className="font-semibold text-green-700">
                {framework.compliant}
              </span>
              <span className="text-green-600/70">Pass</span>
            </div>
            <div className="flex flex-col items-center p-2 rounded bg-yellow-500/10">
              <span className="font-semibold text-yellow-700">
                {framework.partial}
              </span>
              <span className="text-yellow-600/70">Partial</span>
            </div>
            <div className="flex flex-col items-center p-2 rounded bg-red-500/10">
              <span className="font-semibold text-red-700">
                {framework.nonCompliant}
              </span>
              <span className="text-red-600/70">Fail</span>
            </div>
          </div>
          <div className="pt-2 border-t text-xs text-muted-foreground">
            <div className="flex justify-between">
              <span>Last Audit:</span>
              <span>
                {new Date(framework.lastAuditDate).toLocaleDateString()}
              </span>
            </div>
            <div className="flex justify-between mt-1">
              <span>Next Due:</span>
              <span>
                {new Date(framework.nextAuditDue).toLocaleDateString()}
              </span>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

function ComplianceTrendChart({ data }: { data: ComplianceTrend[] }) {
  return (
    <ChartContainer config={{}} className="h-75">
      <LineChart data={data}>
        <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
        <XAxis
          dataKey="date"
          className="text-xs"
          tickLine={false}
          axisLine={false}
        />
        <YAxis
          className="text-xs"
          tickLine={false}
          axisLine={false}
          domain={[0, 100]}
        />
        <ChartTooltip content={<ChartTooltipContent />} />
        <Legend />
        <Line
          type="monotone"
          dataKey="score"
          stroke="#3b82f6"
          strokeWidth={2}
          dot={{ r: 4 }}
          name="Compliance Score (%)"
        />
      </LineChart>
    </ChartContainer>
  );
}

function FrameworkDistributionChart({
  frameworks,
}: {
  frameworks: ComplianceFrameworkSummary[];
}) {
  const data = frameworks.map((f) => ({
    name: f.name,
    score: f.score,
    fill: FRAMEWORK_COLORS[f.id],
  }));

  return (
    <ChartContainer config={{}} className="h-62.5">
      <BarChart data={data} layout="vertical">
        <CartesianGrid
          strokeDasharray="3 3"
          className="stroke-muted"
          horizontal={false}
        />
        <XAxis
          type="number"
          className="text-xs"
          tickLine={false}
          axisLine={false}
          domain={[0, 100]}
        />
        <YAxis
          dataKey="name"
          type="category"
          className="text-xs"
          tickLine={false}
          axisLine={false}
          width={120}
        />
        <ChartTooltip content={<ChartTooltipContent />} />
        <Bar dataKey="score" radius={[0, 4, 4, 0]} />
      </BarChart>
    </ChartContainer>
  );
}

function ControlStatusBadge({ status }: { status: ControlStatus }) {
  const config = {
    compliant: {
      icon: CheckCircle,
      className: "bg-green-500/10 text-green-700 border-green-500/20",
      label: "Compliant",
    },
    partial: {
      icon: AlertTriangle,
      className: "bg-yellow-500/10 text-yellow-700 border-yellow-500/20",
      label: "Partial",
    },
    "non-compliant": {
      icon: XCircle,
      className: "bg-red-500/10 text-red-700 border-red-500/20",
      label: "Non-compliant",
    },
    "not-applicable": {
      icon: Shield,
      className: "bg-gray-500/10 text-gray-700 border-gray-500/20",
      label: "Not Applicable",
    },
  };

  const { icon: Icon, className, label } = config[status];

  return (
    <Badge variant="outline" className={className}>
      <Icon className="h-3 w-3 mr-1" />
      {label}
    </Badge>
  );
}

function SeverityBadge({ severity }: { severity: string }) {
  const colors = {
    low: "bg-green-500/10 text-green-700 border-green-500/20",
    medium: "bg-yellow-500/10 text-yellow-700 border-yellow-500/20",
    high: "bg-red-500/10 text-red-700 border-red-500/20",
    critical: "bg-red-900/10 text-red-900 border-red-900/20",
  };

  return (
    <Badge
      variant="outline"
      className={colors[severity as keyof typeof colors]}
    >
      {severity.toUpperCase()}
    </Badge>
  );
}

function ControlsTable({ controls }: { controls: ComplianceControl[] }) {
  const [filterFramework, setFilterFramework] = React.useState<string>("all");
  const [filterStatus, setFilterStatus] = React.useState<string>("all");
  const [searchTerm, setSearchTerm] = React.useState("");

  const filteredControls = controls.filter((control) => {
    if (filterFramework !== "all" && control.framework !== filterFramework)
      return false;
    if (filterStatus !== "all" && control.status !== filterStatus) return false;
    if (searchTerm) {
      const search = searchTerm.toLowerCase();
      return (
        control.name.toLowerCase().includes(search) ||
        control.description.toLowerCase().includes(search) ||
        control.category.toLowerCase().includes(search)
      );
    }
    return true;
  });

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap gap-2">
        <div className="relative flex-1 min-w-50 max-w-75">
          <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search controls..."
            className="pl-9"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>
        <Select value={filterFramework} onValueChange={setFilterFramework}>
          <SelectTrigger className="w-45">
            <Filter className="h-4 w-4 mr-2" />
            <SelectValue placeholder="Framework" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Frameworks</SelectItem>
            <SelectItem value="ISO27001">ISO 27001/27002</SelectItem>
            <SelectItem value="SOC2">SOC 2</SelectItem>
            <SelectItem value="NIS2">NIS2</SelectItem>
            <SelectItem value="ZERO_TRUST">Zero Trust</SelectItem>
          </SelectContent>
        </Select>
        <Select value={filterStatus} onValueChange={setFilterStatus}>
          <SelectTrigger className="w-37.5">
            <Shield className="h-4 w-4 mr-2" />
            <SelectValue placeholder="Status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Status</SelectItem>
            <SelectItem value="compliant">Compliant</SelectItem>
            <SelectItem value="partial">Partial</SelectItem>
            <SelectItem value="non-compliant">Non-compliant</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <div className="rounded-md border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Control</TableHead>
              <TableHead>Framework</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Risk</TableHead>
              <TableHead>Last Assessed</TableHead>
              <TableHead>Next Due</TableHead>
              <TableHead className="text-right">Evidence</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredControls.map((control) => (
              <TableRow key={control.id}>
                <TableCell>
                  <div>
                    <div className="font-medium">{control.name}</div>
                    <div className="text-xs text-muted-foreground mt-0.5">
                      {control.description}
                    </div>
                    <div className="text-xs text-muted-foreground mt-1">
                      Category: {control.category}
                    </div>
                  </div>
                </TableCell>
                <TableCell>
                  <Badge variant="secondary" className="text-xs">
                    {control.frameworkName}
                  </Badge>
                </TableCell>
                <TableCell>
                  <ControlStatusBadge status={control.status} />
                </TableCell>
                <TableCell>
                  <SeverityBadge severity={control.riskLevel} />
                </TableCell>
                <TableCell className="text-sm text-muted-foreground">
                  {new Date(control.lastAssessed).toLocaleDateString()}
                </TableCell>
                <TableCell className="text-sm text-muted-foreground">
                  {new Date(control.nextAssessmentDue).toLocaleDateString()}
                </TableCell>
                <TableCell className="text-right">
                  <div className="flex justify-end gap-1">
                    {control.evidenceSources.map((source, idx) => (
                      <Link key={idx} href={source} target="_blank">
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-8 w-8 p-0"
                        >
                          <ExternalLink className="h-4 w-4" />
                        </Button>
                      </Link>
                    ))}
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}

function IdentityComplianceTable({
  items,
}: {
  items: IdentityComplianceItem[];
}) {
  const typeLabels: Record<string, string> = {
    privileged: "Privileged Account",
    dormant: "Dormant Account",
    token_expiry: "Token Expiry",
    over_permissioned: "Over-permissioned",
    no_mfa: "No MFA",
  };

  const typeIcons: Record<string, React.ElementType> = {
    privileged: Key,
    dormant: Users,
    token_expiry: Clock,
    over_permissioned: ShieldAlert,
    no_mfa: Lock,
  };

  return (
    <div className="rounded-md border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Type</TableHead>
            <TableHead>Subject</TableHead>
            <TableHead>Severity</TableHead>
            <TableHead>Description</TableHead>
            <TableHead>Detected</TableHead>
            <TableHead className="text-right">Report</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {items.map((item) => {
            const Icon = typeIcons[item.type];
            return (
              <TableRow key={item.id}>
                <TableCell>
                  <div className="flex items-center gap-2">
                    <Icon className="h-4 w-4 text-muted-foreground" />
                    <span className="text-sm">{typeLabels[item.type]}</span>
                  </div>
                </TableCell>
                <TableCell>
                  <div>
                    <div className="font-medium">{item.subjectName}</div>
                    <div className="text-xs text-muted-foreground">
                      {item.subjectId} • {item.subjectType}
                    </div>
                  </div>
                </TableCell>
                <TableCell>
                  <SeverityBadge severity={item.severity} />
                </TableCell>
                <TableCell className="text-sm max-w-75 truncate">
                  {item.description}
                </TableCell>
                <TableCell className="text-sm text-muted-foreground">
                  {new Date(item.detectedAt).toLocaleDateString()}
                </TableCell>
                <TableCell className="text-right">
                  <Link href={item.linkedReportUrl}>
                    <Button variant="ghost" size="sm" className="gap-1">
                      {item.linkedReport}
                      <ChevronRight className="h-4 w-4" />
                    </Button>
                  </Link>
                </TableCell>
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
    </div>
  );
}

function PolicyComplianceTable({ items }: { items: PolicyComplianceItem[] }) {
  return (
    <div className="rounded-md border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Policy</TableHead>
            <TableHead>Status</TableHead>
            <TableHead>Coverage</TableHead>
            <TableHead>Exceptions</TableHead>
            <TableHead>Rules</TableHead>
            <TableHead>Enforcement</TableHead>
            <TableHead>Last Modified</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {items.map((item) => (
            <TableRow key={item.id}>
              <TableCell>
                <div>
                  <div className="font-medium">{item.policyName}</div>
                  <div className="text-xs text-muted-foreground">
                    {item.policyId}
                  </div>
                </div>
              </TableCell>
              <TableCell>
                <Badge
                  variant={item.status === "active" ? "default" : "secondary"}
                  className={cn(
                    item.status === "active" &&
                      "bg-green-500/10 text-green-700 border-green-500/20",
                  )}
                >
                  {item.status}
                </Badge>
              </TableCell>
              <TableCell>
                <div className="flex items-center gap-2">
                  <div className="w-16 h-2 bg-muted rounded-full overflow-hidden">
                    <div
                      className={cn(
                        "h-full rounded-full",
                        item.coverage >= 90
                          ? "bg-green-500"
                          : item.coverage >= 70
                            ? "bg-yellow-500"
                            : "bg-red-500",
                      )}
                      style={{ width: `${item.coverage}%` }}
                    />
                  </div>
                  <span className="text-sm">{item.coverage}%</span>
                </div>
              </TableCell>
              <TableCell>
                <Badge
                  variant={
                    item.exceptionsCount === 0 ? "secondary" : "destructive"
                  }
                >
                  {item.exceptionsCount}
                </Badge>
              </TableCell>
              <TableCell className="text-sm text-muted-foreground">
                {item.explicitRules} explicit / {item.inheritedRules} inherited
              </TableCell>
              <TableCell>
                <div className="flex items-center gap-2">
                  <div className="w-16 h-2 bg-muted rounded-full overflow-hidden">
                    <div
                      className={cn("h-full rounded-full bg-blue-500")}
                      style={{ width: `${item.enforcementRate}%` }}
                    />
                  </div>
                  <span className="text-sm">{item.enforcementRate}%</span>
                </div>
              </TableCell>
              <TableCell className="text-sm text-muted-foreground">
                {new Date(item.lastModified).toLocaleDateString()}
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}

function GapsTable({ gaps }: { gaps: ComplianceGap[] }) {
  return (
    <div className="rounded-md border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Gap ID</TableHead>
            <TableHead>Control</TableHead>
            <TableHead>Framework</TableHead>
            <TableHead>Severity</TableHead>
            <TableHead>Description</TableHead>
            <TableHead>Remediation Due</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {gaps.map((gap) => (
            <TableRow key={gap.id}>
              <TableCell className="font-mono text-xs">{gap.id}</TableCell>
              <TableCell>
                <div className="font-medium">{gap.controlName}</div>
                <div className="text-xs text-muted-foreground">
                  {gap.controlId}
                </div>
              </TableCell>
              <TableCell>
                <Badge variant="outline">{gap.framework}</Badge>
              </TableCell>
              <TableCell>
                <SeverityBadge severity={gap.severity} />
              </TableCell>
              <TableCell className="text-sm max-w-62.5">
                {gap.description}
              </TableCell>
              <TableCell>
                <div className="flex flex-col">
                  <span className="text-sm">
                    {new Date(gap.remediationDeadline!).toLocaleDateString()}
                  </span>
                  {gap.daysOverdue !== undefined && gap.daysOverdue > 0 && (
                    <span className="text-xs text-red-600 font-medium">
                      {gap.daysOverdue} days overdue
                    </span>
                  )}
                </div>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}

function EvidenceExportSection() {
  const [exportFormat, setExportFormat] = React.useState<string>("audit-pack");
  const [dateRange, setDateRange] = React.useState<string>("last-30-days");

  const handleExport = () => {
    console.log(
      `Exporting compliance report: ${exportFormat}, range: ${dateRange}`,
    );
  };

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Download className="h-5 w-5" />
              Export Compliance Report
            </CardTitle>
            <CardDescription>
              Generate machine-readable audit evidence for external auditors
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Export Format</label>
              <Select value={exportFormat} onValueChange={setExportFormat}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="audit-pack">
                    <div className="flex items-center gap-2">
                      <FileCheck className="h-4 w-4" />
                      Audit Pack (ZIP with JSON + Logs)
                    </div>
                  </SelectItem>
                  <SelectItem value="csv">
                    <div className="flex items-center gap-2">
                      <FileText className="h-4 w-4" />
                      CSV (Controls + Evidence)
                    </div>
                  </SelectItem>
                  <SelectItem value="json">
                    <div className="flex items-center gap-2">
                      <FileText className="h-4 w-4" />
                      JSON (Machine-readable)
                    </div>
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium">Date Range</label>
              <Select value={dateRange} onValueChange={setDateRange}>
                <SelectTrigger>
                  <Calendar className="h-4 w-4 mr-2" />
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="last-7-days">Last 7 days</SelectItem>
                  <SelectItem value="last-30-days">Last 30 days</SelectItem>
                  <SelectItem value="last-90-days">Last 90 days</SelectItem>
                  <SelectItem value="last-year">Last year</SelectItem>
                  <SelectItem value="all-time">All time</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <Button onClick={handleExport} className="w-full">
              <Download className="h-4 w-4 mr-2" />
              Generate Export
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <History className="h-5 w-5" />
              Evidence Sources
            </CardTitle>
            <CardDescription>
              Data sources aggregated in this compliance report
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {[
                {
                  name: "Identity Management System",
                  status: "connected",
                  lastSync: "2 min ago",
                },
                {
                  name: "Access Decision Logs",
                  status: "connected",
                  lastSync: "5 min ago",
                },
                {
                  name: "Policy Engine",
                  status: "connected",
                  lastSync: "1 min ago",
                },
                {
                  name: "Audit Trail Database",
                  status: "connected",
                  lastSync: "3 min ago",
                },
                {
                  name: "Dormant Account Scanner",
                  status: "connected",
                  lastSync: "1 hour ago",
                },
              ].map((source) => (
                <div
                  key={source.name}
                  className="flex items-center justify-between p-3 rounded-lg bg-muted/50"
                >
                  <div className="flex items-center gap-3">
                    <div
                      className={cn(
                        "h-2.5 w-2.5 rounded-full",
                        source.status === "connected"
                          ? "bg-green-500"
                          : "bg-red-500",
                      )}
                    />
                    <span className="text-sm font-medium">{source.name}</span>
                  </div>
                  <span className="text-xs text-muted-foreground">
                    Synced {source.lastSync}
                  </span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Audit Trail Access Log</CardTitle>
          <CardDescription>
            This page access is audited. Recent compliance report views:
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-2">
            {[
              {
                user: "auditor@external-firm.com",
                action: "Viewed compliance summary",
                timestamp: "2025-02-09T09:45:00Z",
                ip: "203.0.113.42",
              },
              {
                user: "compliance-officer@aether.io",
                action: "Exported audit pack",
                timestamp: "2025-02-08T16:30:00Z",
                ip: "198.51.100.15",
              },
              {
                user: "security-admin@aether.io",
                action: "Viewed control details",
                timestamp: "2025-02-08T14:20:00Z",
                ip: "198.51.100.22",
              },
            ].map((entry, idx) => (
              <div
                key={idx}
                className="flex items-center justify-between p-3 rounded-lg border text-sm"
              >
                <div className="flex items-center gap-4">
                  <Eye className="h-4 w-4 text-muted-foreground" />
                  <span className="font-medium">{entry.user}</span>
                  <span className="text-muted-foreground">{entry.action}</span>
                </div>
                <div className="flex items-center gap-4 text-muted-foreground">
                  <code className="text-xs bg-muted px-2 py-0.5 rounded">
                    {entry.ip}
                  </code>
                  <span>{new Date(entry.timestamp).toLocaleString()}</span>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// ==================== MAIN PAGE ====================

export default function ComplianceReportPage() {
  const [activeTab, setActiveTab] = React.useState("overview");

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">
            Compliance Report
          </h1>
          <p className="text-muted-foreground mt-1">
            Evidence-based compliance monitoring and audit readiness for
            identity governance
          </p>
        </div>
        <div className="flex items-center gap-4">
          <div className="text-right">
            <div className="text-sm text-muted-foreground">
              Report Generated
            </div>
            <div className="text-sm font-medium">
              <TimeDisplay />
            </div>
          </div>
          <Badge variant="outline" className="bg-blue-500/10 text-blue-700">
            <Shield className="h-3 w-3 mr-1" />
            Read-Only
          </Badge>
        </div>
      </div>

      {/* Navigation to Related Reports */}
      <div className="flex flex-wrap gap-2">
        <Link href="/admin/report/access">
          <Button variant="outline" size="sm" className="gap-1">
            Access Report
            <ExternalLink className="h-3 w-3" />
          </Button>
        </Link>
        <Link href="/admin/report/privilege">
          <Button variant="outline" size="sm" className="gap-1">
            Privilege Report
            <ExternalLink className="h-3 w-3" />
          </Button>
        </Link>
        <Link href="/admin/report/dormant">
          <Button variant="outline" size="sm" className="gap-1">
            Dormant Accounts
            <ExternalLink className="h-3 w-3" />
          </Button>
        </Link>
        <Link href="/security/audit">
          <Button variant="outline" size="sm" className="gap-1">
            Audit Logs
            <ExternalLink className="h-3 w-3" />
          </Button>
        </Link>
        <Link href="/platform/policy">
          <Button variant="outline" size="sm" className="gap-1">
            Policy Engine
            <ExternalLink className="h-3 w-3" />
          </Button>
        </Link>
      </div>

      {/* Main Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="grid w-full grid-cols-6 lg:w-200">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="controls">Controls</TabsTrigger>
          <TabsTrigger value="identity">Identity</TabsTrigger>
          <TabsTrigger value="policies">Policies</TabsTrigger>
          <TabsTrigger value="gaps">Gaps</TabsTrigger>
          <TabsTrigger value="evidence">Evidence</TabsTrigger>
        </TabsList>

        {/* OVERVIEW TAB */}
        <TabsContent value="overview" className="space-y-6 mt-6">
          <ComplianceScoreCard summary={COMPLIANCE_SUMMARY} />

          <div className="grid gap-4 lg:grid-cols-2">
            <Card>
              <CardHeader>
                <CardTitle>Compliance Trend (6 months)</CardTitle>
                <CardDescription>
                  Overall compliance score evolution over time
                </CardDescription>
              </CardHeader>
              <CardContent>
                <ComplianceTrendChart data={COMPLIANCE_SUMMARY.trend} />
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Framework Scores</CardTitle>
                <CardDescription>
                  Compliance scores by regulatory framework
                </CardDescription>
              </CardHeader>
              <CardContent>
                <FrameworkDistributionChart
                  frameworks={COMPLIANCE_SUMMARY.frameworks}
                />
              </CardContent>
            </Card>
          </div>

          <div>
            <h3 className="text-lg font-semibold mb-4">Framework Compliance</h3>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
              {COMPLIANCE_SUMMARY.frameworks.map((framework) => (
                <FrameworkCard key={framework.id} framework={framework} />
              ))}
            </div>
          </div>
        </TabsContent>

        {/* CONTROLS TAB */}
        <TabsContent value="controls" className="space-y-6 mt-6">
          <Card>
            <CardHeader>
              <CardTitle>Compliance Controls</CardTitle>
              <CardDescription>
                Detailed view of all controls, their status, and associated
                evidence
              </CardDescription>
            </CardHeader>
            <CardContent>
              <ControlsTable controls={COMPLIANCE_CONTROLS} />
            </CardContent>
          </Card>
        </TabsContent>

        {/* IDENTITY TAB */}
        <TabsContent value="identity" className="space-y-6 mt-6">
          <Card>
            <CardHeader>
              <div className="flex items-start justify-between">
                <div>
                  <CardTitle>Identity & Access Compliance</CardTitle>
                  <CardDescription>
                    Compliance violations and gaps related to identity
                    management
                  </CardDescription>
                </div>
                <div className="flex gap-2">
                  <Badge variant="destructive">
                    {IDENTITY_COMPLIANCE_ITEMS.length} Issues
                  </Badge>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <IdentityComplianceTable items={IDENTITY_COMPLIANCE_ITEMS} />
            </CardContent>
          </Card>

          <div className="grid gap-4 md:grid-cols-3">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <CardTitle className="text-sm font-medium">
                  Privileged Accounts
                </CardTitle>
                <Key className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">234</div>
                <p className="text-xs text-muted-foreground">
                  <Link
                    href="/admin/report/privilege"
                    className="text-blue-600 hover:underline"
                  >
                    View in Privilege Report →
                  </Link>
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <CardTitle className="text-sm font-medium">
                  Dormant Accounts
                </CardTitle>
                <Users className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">47</div>
                <p className="text-xs text-muted-foreground">
                  <Link
                    href="/admin/report/dormant"
                    className="text-blue-600 hover:underline"
                  >
                    View in Dormant Report →
                  </Link>
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <CardTitle className="text-sm font-medium">
                  Access Decisions
                </CardTitle>
                <Shield className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">45,892</div>
                <p className="text-xs text-muted-foreground">
                  <Link
                    href="/admin/report/access"
                    className="text-blue-600 hover:underline"
                  >
                    View in Access Report →
                  </Link>
                </p>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* POLICIES TAB */}
        <TabsContent value="policies" className="space-y-6 mt-6">
          <Card>
            <CardHeader>
              <div className="flex items-start justify-between">
                <div>
                  <CardTitle>Policy Enforcement Compliance</CardTitle>
                  <CardDescription>
                    Policy coverage, exceptions, and enforcement metrics
                  </CardDescription>
                </div>
                <Link href="/platform/policy">
                  <Button variant="outline" size="sm" className="gap-1">
                    Manage Policies
                    <ExternalLink className="h-3 w-3" />
                  </Button>
                </Link>
              </div>
            </CardHeader>
            <CardContent>
              <PolicyComplianceTable items={POLICY_COMPLIANCE_ITEMS} />
            </CardContent>
          </Card>

          <div className="grid gap-4 md:grid-cols-2">
            <Card>
              <CardHeader>
                <CardTitle>Policy Coverage Overview</CardTitle>
                <CardDescription>
                  Coverage across all identity types and resources
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {[
                    { label: "User Identities", value: 94, total: 1247 },
                    { label: "Service Accounts", value: 89, total: 456 },
                    { label: "API Resources", value: 98, total: 892 },
                    { label: "Infrastructure", value: 87, total: 234 },
                  ].map((item) => (
                    <div key={item.label} className="space-y-2">
                      <div className="flex justify-between text-sm">
                        <span>{item.label}</span>
                        <span className="text-muted-foreground">
                          {item.value}% ({item.total} items)
                        </span>
                      </div>
                      <div className="h-2 bg-muted rounded-full overflow-hidden">
                        <div
                          className={cn(
                            "h-full rounded-full transition-all",
                            item.value >= 90
                              ? "bg-green-500"
                              : item.value >= 70
                                ? "bg-yellow-500"
                                : "bg-red-500",
                          )}
                          style={{ width: `${item.value}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Active Exceptions</CardTitle>
                <CardDescription>
                  Temporary policy exceptions requiring review
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {[
                    {
                      policy: "Time-based Access Window",
                      subject: "emergency-oncall@aether.io",
                      reason: "24/7 emergency access required",
                      expires: "2025-03-01",
                    },
                    {
                      policy: "IP Whitelist - Corporate",
                      subject: "remote-contractor-01",
                      reason: "Remote contractor VPN alternative",
                      expires: "2025-02-28",
                    },
                    {
                      policy: "Require MFA for Production",
                      subject: "legacy-integration-svc",
                      reason: "Service account migration in progress",
                      expires: "2025-02-15",
                    },
                  ].map((exception, idx) => (
                    <div
                      key={idx}
                      className="flex items-start justify-between p-3 rounded-lg border text-sm"
                    >
                      <div>
                        <div className="font-medium">{exception.policy}</div>
                        <div className="text-muted-foreground">
                          {exception.subject}
                        </div>
                        <div className="text-xs text-muted-foreground mt-1">
                          {exception.reason}
                        </div>
                      </div>
                      <Badge variant="outline" className="text-xs">
                        Expires{" "}
                        {new Date(exception.expires).toLocaleDateString()}
                      </Badge>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* GAPS TAB */}
        <TabsContent value="gaps" className="space-y-6 mt-6">
          <Card>
            <CardHeader>
              <div className="flex items-start justify-between">
                <div>
                  <CardTitle>Risk & Gap Analysis</CardTitle>
                  <CardDescription>
                    Identified compliance gaps requiring remediation
                  </CardDescription>
                </div>
                <div className="flex gap-2">
                  <Badge variant="destructive">
                    <AlertTriangle className="h-3 w-3 mr-1" />
                    {COMPLIANCE_GAPS.length} Open Gaps
                  </Badge>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <GapsTable gaps={COMPLIANCE_GAPS} />
            </CardContent>
          </Card>

          <div className="grid gap-4 md:grid-cols-4">
            <Card className="bg-red-50/50">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-red-700">
                  Critical Gaps
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold text-red-700">
                  {
                    COMPLIANCE_GAPS.filter((g) => g.severity === "critical")
                      .length
                  }
                </div>
              </CardContent>
            </Card>
            <Card className="bg-orange-50/50">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-orange-700">
                  High Risk Gaps
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold text-orange-700">
                  {COMPLIANCE_GAPS.filter((g) => g.severity === "high").length}
                </div>
              </CardContent>
            </Card>
            <Card className="bg-yellow-50/50">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-yellow-700">
                  Medium Risk
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold text-yellow-700">
                  {
                    COMPLIANCE_GAPS.filter((g) => g.severity === "medium")
                      .length
                  }
                </div>
              </CardContent>
            </Card>
            <Card className="bg-green-50/50">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-green-700">
                  Remediated (30d)
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold text-green-700">12</div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* EVIDENCE TAB */}
        <TabsContent value="evidence" className="space-y-6 mt-6">
          <EvidenceExportSection />
        </TabsContent>
      </Tabs>

      {/* Footer Disclaimer */}
      <div className="pt-6 border-t">
        <div className="flex items-start gap-3 text-sm text-muted-foreground">
          <Gavel className="h-5 w-5 shrink-0 mt-0.5" />
          <div>
            <p className="font-medium">Compliance Disclaimer</p>
            <p className="mt-1">
              This report provides evidence-based compliance status based on
              automated assessments and manual reviews. It does not constitute a
              certification. All data is read-only and sourced from verified
              audit trails. Access to this page is logged and monitored.
            </p>
            <p className="mt-2">
              For certification purposes, please engage with qualified auditors.
              This platform facilitates audit readiness but does not replace
              formal compliance assessments.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
